### ISSUE TITLE
[feature request] add an option to view the "decompiled" code with values in hex

### ISSUE THREAD

**Issue by meleu** [Jamiras/RATools#1]
I think the image below says what I mean:

![ratools-suggestion](https://user-images.githubusercontent.com/8508804/33545761-4b60a7ba-d8c6-11e7-98b2-5dc0c50cd01c.png)

**Comment by Jamiras** [comment]
I've added a "View" menu with a "Hexadecimal Values" option:
![image](https://user-images.githubusercontent.com/32680403/33749260-01089b3e-db8a-11e7-8aa6-9beb899bf62a.png)

This toggles the display of values in the viewer pane. It has no effect on addresses, which are always displayed in hexadecimal.
