### ISSUE TITLE
add function to generate pause-lock (PauseIf and ResetIf in different groups)

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#106]
I ran into this situation whilst adding cheat protection to a set.

Let's say this achievement existed:
```
function boss_beaten() => byte(0xbabe) == 1
achievement(title="test", description="test", points=5, trigger=boss_beaten())
```

Now, let's say that there's a cheat code that refills the player's health and that can be used anywhere in the stage where the boss resides. Let's also say I have ways to know the stage id and to detect the cheat being used:
```
function in_stage_1() => byte(0x1234) == 1
function cheated() => prev(byte(0x1000)) > byte(0x1000)
```

To protect against the cheat code being used, I wanted to use the following pattern:
```
Core:
// boss beaten
        Mem(0xbabe) == Value(1)
// reset if not in boss' stage (meant to eventually reset the PauseIf in Alt 1)
ResetIf Mem(0x1234) != Value(1)

Alt 1:
// block the achievement if the cheat is used (meant to reset when the player leaves the stage)
PauseIf Delta(0x1000) > Mem(0x1000) (Hit target = 1)
```

I tried to generate that pattern like this:
```
function boss_beaten() => byte(0xbabe) == 1
function in_stage_1() => byte(0x1234) == 1
function cheated() => prev(byte(0x1000)) > byte(0x1000)

achievement(
    title="test", description="test", points=5,
    trigger=(
        (boss_beaten() && never(!in_stage_1())
        || unless(once(cheated()))
    )
)
```

However, the generated achievement ends up having an empty core group and 2 alt groups. Because the PauseIf's alt group is always true as well, the achievement always triggers immediately.

```
Core:
Value(1) == Value(1)

Alt 1:
        Mem(0xbabe) == Value(1)
ResetIf Mem(0x1234) != Value(1)

Alt 2:
PauseIf Delta(0x1000) > Mem(0x1000) (Hit target = 1)
```

I managed to find a way to make this work, but at the cost of introducing an unnecessary always-false alt group:

```
function boss_beaten() => byte(0xbabe) == 1
function in_stage_1() => byte(0x1234) == 1
function cheated() => prev(byte(0x1000)) > byte(0x1000)

achievement(
    title="test", description="test", points=5,
    trigger=(
        (boss_beaten() && never(!in_stage_1())
        && (always_false() || unless(once(cheated())))
    )
)
```
```
Core:
        Mem(0xbabe) == Value(1)
ResetIf Mem(0x1234) != Value(1)

Alt 1:
Value(1) == Value(0)

Alt 2:
PauseIf Delta(0x1000) > Mem(0x1000) (Hit target = 1)
```

I ended up using this solution and deleting the extra alt group manually in the achievement editor before committing.

------

Even though I did find a workaround, it feels like there's something missing in RATools to properly support PauseIfs with hit targets coupled with ResetIfs in other alt groups.

Adding credence to this is also the fact that loading the achievement from the server breaks it by moving the PauseIf into the core group, where it can never be reset. You can see this happening by loading this achievement: https://retroachievements.org/Achievement/54288

**Comment by Jamiras** [comment]
I think your workaround is the correct solution. If you have:
```
trigger = (a == 1) || (b == 1)
```
You want two alt groups and no core group. 

By adding the always_false, you make it clear what you want to be the core group and what you want to be the alt groups:
```
trigger = (a == 1) && (always_false() || b == 1)
```
I think optimizing out the always_false is reasonable.

I don't think providing a mechanism to automatically generate the alt group separated from the resetif is reasonable as there are use cases where you want the pauseif in the core group, and others where you want it in an alt group.

> Adding credence to this is also the fact that loading the achievement from the server breaks it by moving the PauseIf into the core group, where it can never be reset.

This doesn't seem right. Achievements from the server are never modified by the processing code. You can check the same condition a hundred times in a single achievement and the runtime will blindly make the same check a hunder times.

The referenced achievement seems to be loading a segregated PauseIf just fine:
![image](https://user-images.githubusercontent.com/32680403/72229571-f0263f80-356c-11ea-9ef9-6e88397573cc.png)

**Comment by gdeOo** [comment]
I'm fine with the workaround, the other issues were the main problem.

You misunderstood what I meant by loading. I was talking about loading the achievement from the server into RATools. I haven't tested since, but I believe what happened was that the generated rascript code would compile down to an achievement that was not equivalent to what was in the server, because the `PauseIf` was moved.

It's unfortunate that some achievements require us to think of alts, even though for most of them we just write an expression and let the optimizer put things where it wants to. That's what I meant when I said it feels like something's missing.

**Comment by Jamiras** [comment]
I view the pauselock as an unintended feature. It only really works when it's the only PauseIf/ResetIf in the trigger.

However, it is used frequently enough that it could warrant its own syntax.

Maybe instead of writing
```
repeated(1, unless(byte(0x1234) == 1)) && (always_false() || never(byte(0x2345) == 2)))
```
Something like:
```
disable(when=byte(0x1234) == 1, until=byte(0x2345) == 2)
```
I'm going to have to think about the permutations of generating from this. 

It'll probably have to put the PauseIf in the core, regardless of where the disable appears. Then put the ResetIf in a separate Alt with an always_false() to prevent it from being true by itself. 

What if the trigger has multiple `disable` clauses? Then the PauseIfs should be in individual alt groups with all the ResetIfs in the core, but what if there's additional alts? The PauseIfs wouldn't affect the additional alts unless they're spread across them.

Additionally, what if the user intended that a single PauseIf was only ResetIf by a single condition. With `disable(A until B)` and `disable(C until D)`, if both A and C were true, would B becoming true enable the achievement? Semantically, it should only enable the A clause and leave the C clause disabled. Figuring out these permutations is much more complex, and potentially impossible with the current toolset.

I will continue to think about a way to simplify this, but for now, I think manually generating the logic is the easiest solution.

**Comment by Jamiras** [comment]
> You misunderstood what I meant by loading. I was talking about loading the achievement from the server into RATools. 

Yes, I did. I will update the dumper to better handle this case.

**Comment by gdeOo** [comment]
That `disable` function does look like a nice solution, but I understand that it's hard to make it work for all cases. That's why I didn't even propose a solution, couldn't come up with one.

For the specific scenarios you described, I think either enforcing a one-`disable`-per-achievement rule, or documenting how multiple `disables` would be combined into a single `disable` could work out. Allowing only one `disable` would probably get rid of most corner cases. Would be worse for composition, but you'd still be able to compose the triggers passed into the `disable`, so it shouldn't be much of a problem.

**Comment by Jamiras** [comment]
This can be accomplished now with `ResetNextIf` without having to worry about the permutations related to alt groups:
```
unless(once(byte(0x1234) == 1 && never(byte(0x2345) == 2))))
```
Becomes:
```
ResetNextIf byte(0x2345) == 2
PauseIf     byte(0x1234) == 1 (1)
```

It's still a bit more verbose and harder to read than having a special function. As suggested above:
```
disable(when=byte(0x1234) == 1, until=byte(0x2345) == 2)
```
