### ISSUE TITLE
Error in mathematical expression: Cannot generate trigger from IntegerConstant

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#111]
Ran into an issue with the processing of a mathematical expression.

Minimal example:
```
achievement(
    title="test", description="test", points=5,
    trigger=5 - byte(0x1234) < 2
)
```
This results in the following error: `Cannot generate trigger from IntegerConstant`. The problem seems to happen when RATools attempts to replace the subtraction with an addition.

**Comment by Jamiras** [comment]
The problem actually stems from the `SubSource`. The resulting code would be:
```
SubSource 8-bit 0x1234
          Value      5 < 2
```
And the temporary construction of the left side fails because "5" isn't a memory reference
