### ISSUE TITLE
Common conditions in ORed groups wrapped in repeated() are deleted

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#115]
This seems to be a bug where conditions are "optimized out" incorrectly.

An example case can be generated using [this script](https://pastebin.com/raw/8T6zPv4P) as a base. In `force_dobon_trigger()`, remove `+ LOST_SET_OFFSET` in the last condition definition, such that both of the condition groups wrapped in the `repeated()` call share a common condition. The result is that the condition is no longer present anywhere in the condition set.

I believe it should instead become a group-level condition.

**Comment by Jamiras** [comment]
This can be simplified to:
```
achievement(
    title = "Test", description = "Test", points = 5,
    trigger = repeated(3, (byte(0x1234) == 2 && byte(0x1235) == 3) || (byte(0x1234) == 3 && byte(0x1235) == 3)
)
```
Which generates:
```
AddHits byte(0x1234) == 2
        byte(0x1234) == 3 (3)
```
The logic that converts `repeated(n, A || B)` expects A and B to end up solely as alt groups in a temporary achievement and converts them into a series of `AddHits` clauses. The clause that was promoted to core in the temporary achievement is lost.
