### ISSUE TITLE
rich_presence_value() does not recognize an explicit "VALUE" format

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#116]
The documentation lists `VALUE` as one of the possible `format` values in rich presence definition, but when set explicitly RATools does not recognize it.

**Comment by Jamiras** [comment]
Please clarify.
```
rich_presence_display("{0}",
    rich_presence_value("test", byte(0x1234), "VALUE")
)
```
works just fine. 

The list of supported formats is here: https://github.com/Jamiras/RATools/blob/master/Data/Leaderboard.cs#L51-L86

**Comment by rzumer** [comment]
I guess that was my mistake as I wrote VALUE as a constant, not a string.
