### ISSUE TITLE
AddAddress is not always generated as expected

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#117]
```
DYNAMIC_DATA_PTR = word(0x106584)
function cur_page() => byte(DYNAMIC_DATA_PTR + 0x260000 - 76)
trigger = prev(cur_page()) == 0 && cur_page() == 2
```

There are some other conditions added to my trigger (ANDed), but in this scenario AddAddress is only generated the first time. The `cur_page() == 2` condition has no offset at all, so it looks up the address at 0x260000 - 76.

**Comment by Jamiras** [comment]
This was fixed by #108 - in particular the addition of `AddAddress` to the switch statement (via the helper function) here: https://github.com/Jamiras/RATools/commit/177ebc3ea8853c3fda39d03fabd544a46324f9e4#diff-67a6fd57d8598d5abe117dc2916d1ed5L1725
