### ISSUE TITLE
Combining dynamic addressing with SubSource returns an error

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#118]
No sample right now, but I had to replace subtraction operators with addition ones, and then manually replace AddSource with SubSource, in order to get a condition set involving subtracting the delta of a dynamically-addressed memory location from its current value.

**Comment by Jamiras** [comment]
I created this:
```
achievement(
    title = "Test", description = "Test", points = 5,
    trigger = byte(word(0x1111)) - prev(byte(word(0x1111))) > 1
)
```
From your description, and it does generate an error "cannot normalize expression for negation". Changing the minus to a plus does eliminate the error, so I can only assume this is the problem you're reporting.
