### ISSUE TITLE
Generated AddHits sequences can never trigger

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#120]
I'm told that for AddHits sequences to trigger, the last condition (the one without AddHits) has to have a hit count. However, when generating such sequences through RATools the hit counter remains at 0, making it invalid.

Example trigger function:
```
function my_trigger() {
    trigger = always_true()

    for f in range(0, 9) {
        sub_trigger = always_false()
        for b in range(0, 127) {
            sub_trigger = sub_trigger || high4(0x1234 + b) == f
        }

        trigger = trigger && once(sub_trigger)
    }

    return trigger
}
```

**Comment by Jamiras** [comment]
Please clarify.

Using the provided code, every 127th condition has a once() wrapper. Simplifying the inner loop to (0, 2) generates this:
![image](https://user-images.githubusercontent.com/32680403/72229345-22cf3880-356b-11ea-9d00-cdcd7e20278b.png)

And the once()s show up correctly as a hit target of 1 in the editor:
![image](https://user-images.githubusercontent.com/32680403/72229372-55793100-356b-11ea-8cf0-48b61ca7f5a8.png)

Tested with current master and 1.6.3

**Comment by Jamiras** [comment]
Closing as not rperoducible.
