### ISSUE TITLE
leaderboard() value parameter doesn't detect usages of prev()

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#139]
I'm attempting to create speedrun leaderboards for individual levels, and to do so, I'm attempting to detect each change in the system timer, as it increments by one for each frame (before inevitably overflowing to 0 when it hits its maximum possible 32-bit value). However, when using this code:

leaderboard(title = "Time Trial: " + levelCode + " - " + levelCodesToLevelInfo[levelCode]["name"],
            description = "Ring the gong in the fastest time you can!",
            start = isLevelCheckpointValid && IsInLevel(),
            cancel = !IsInLevel(),
            submit = isLevelComplete && isLevelCheckpointValid,
            value = measured(frameIncremented()),
            format = "FRAMES")

It compiles the "value" to `d0xX073ac0` instead of `M:0xX073ac0!=d0xX073ac0` as expected.

The definition for `frameIncremented()` is as follows:

`function frameIncremented() => prev(framesCounter()) != framesCounter()`

I have attached my current .rascript file to reproduce the issue. I am currently using RATools 1.6.4.
[Croc Legend of the Gobbos - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/4303841/Croc.Legend.of.the.Gobbos.-.Copy.rascript.txt)

**Comment by Jamiras** [comment]
It wasn't a failure detecting the prev, it was a lack of support for measured(). I've modified the logic to also support measured() in the leaderboard value parameter.
