### ISSUE TITLE
[feature request] length/size function for arrays and dictionaries

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#140]
I've ran into multiple situations in which it'd have been useful to be able to extract the length of an array or dictionary. Could also be applicable to strings.

Some use cases:

```
// accessing array elements by indexing from the back
numbers = [1, 2, 3, 4]
four = number[length(numbers)-1]

// has-every-of kind conditions

items = ['gun', 'bullet', 'key']
n_owned_items = byte(0x1234)
function has_all_items() => n_owned_items == length(items)

items = {
    'gun':    bit0(0x1234),
    'bullet': bit1(0x1234),
    'key':    bit2(0x1234)
}
function has_all_items() {
    val = 0
    for item in items {
        val = val + items[item]
    }
    return val == length(items)
}
```

These could be solved in other ways, but I think having such a function would be a nice QoL improvement.

**Comment by Jamiras** [comment]
For arrays and dictionaries, I'd prefer `count`, but with the inclusion of strings, `length` seems appropriate.

I've considered adding something like this before, but have never needed it myself.
