### ISSUE TITLE
[feature request] string formatting

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#143]
I've run into situations in which the capability to format strings would have saved a bunch of code duplication.

A basic use case:

```
function mission_achievement(mission_name) {
    achievement(
        title=mission_name,
        description=format("Beat {0}", mission_name),
        points=0,
        trigger=mission_completed(mission_name)
    )
}
```

**Comment by Jamiras** [comment]
String concatenation (of both strings and numbers) is already functional.
```
description = "Beat " + mission_name + " (mission " + mission_id ")"
```
However, as we already support a similar syntax for constructing rich presence display strings, I see no reason not to add a `format` function.
