### ISSUE TITLE
Superfluous always-false AddHits due to or'd conditions inside a never(repeated(...))

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#148]
Compiling the following achievement produces code that contains what I believe to be unnecessary `AddHits always_false()` instructions.

```
boss_state = 0x1234
boss_vars = 0x1235
function boss_attacked(n) {
    cond = always_false()
    for i in range(n, n+1) {
        cond = cond || byte(boss_vars + i) == (0x10 + i)
    }
    return cond
}

achievement(
    title="title", description="description", points=5,
    trigger=once(byte(boss_state) == 0x10)
            && byte(boss_state) == 0xff
            && never(repeated(2, boss_attacked(1) || boss_attacked(3)))
)
```

```
once(byte(0x001234) == 16)
byte(0x001234) == 255
AddHits always_false()
AddHits byte(0x001236) == 17
AddHits byte(0x001237) == 18
AddHits always_false()
AddHits byte(0x001238) == 19
never(repeated(2, byte(0x001239) == 20))
```

The issue seems to be related to the existence of the `boss_attacked` function. Each call to it seems to introduce one of the superfluous `AddHits`. The OR'd conditions inside the function are not affected. Similarly, if the conditions are all moved out of the function, the `AddHits` instructions are not generated.

The issue was observed at commit `75ed471d5575b1b38579e3fda20b35c747d441a7`, one commit ahead of `v1.6.4`.

**Comment by gdeOo** [comment]
Also had a similar problem with superfluous `AndNext always_true()`. Was going to open another issue, but I just realized that it's probably the same bug.

```
function array_matches(p, values) {
    cond = always_true()
    for v in values {
        cond = cond && byte(p) == v
        p = p + 1
    }
    return cond
}

achievement(
    title="title", description="description", points=5,
    trigger=never(repeated(2, byte(0x1234) == 0
                              && array_matches(0x1235, [0x61, 0x6b])))
)
```

```
AndNext byte(0x001234) == 0
AndNext always_true()
AndNext byte(0x0012235) == 97
never(repeated(2, byte(0x001236) == 107))
```

Like the `AddHits` case, if the conditions are put directly in the trigger instead of the function, the issue does not happen.

**Comment by Jamiras** [comment]
The problem is that the `AddHits` and `AndNext` are embedded in a multi-condition clause, so the optimizer ignores them. I see the issue both with your code and with the logic directly in the trigger:
```
achievement(\"T\", \"D\", 5, 
    never(repeated(2, always_false() || byte(0x1234) == 1 || 
                      always_false() || byte(0x1235) == 2)))
```
```
AddHits always_false()
AddHits byte(0x001234) == 1
AddHits always_false()
never(repeated(2, byte(0x001235) == 2))
```
Removing the `never(repeated(2,` does allow the optimizer to eliminate them as they end up as standalone alt groups (in the first case) or singular conditions (in the second case).
