### ISSUE TITLE
Changes in repeated() parameter do not properly reflect achievements created via loops as different from local

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#157]
Normally, updating any facet of an achievement (title, description, point value, trigger logic) is supposed to flag it as different and, therefore, allow the developer to update the local version of that achievement to the current one.

If that achievement is generated via a loop, however, and the change in question involves changing the first parameter of repeated(), the IDE doesn't appear to recognize that the achievement is changed (i.e., the change doesn't show up in the diff), even though the change is reflected when you click on the generated achievement in the side pane, as if it matched local.

I've attached my script where I've noticed this behavior (see below). You can see this by going down to the "Premier Engineer" achievement and updating the "threshold" value for the dictionary preceding the loop to a value different than 21.

To work around this, I can simply delete the achievement and then update local again to force the change to go through, but my guess is that this is not intended behavior.

[Legend of Zelda, The Spirit Tracks.rascript.txt](https://github.com/Jamiras/RATools/files/4571595/Legend.of.Zelda.The.Spirit.Tracks.rascript.txt)

**Comment by Jamiras** [comment]
It's seeing the "measured(repeated(21, always_false()))" as identical to the "measured(repeated(20, always_false()))" because `always_false()` should always equal `always_false()`, regardless of the number of hits. It's not accounting for the preceding statements. I will improve the matching logic.
