### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#163]
In the game I'm working on (*The World Ends with You*), I need to check for the existence of certain items in the player's inventory. The inventory is very large--472 slots--and so I'm attempting to use loops to generate the requirements so I don't have to do it by hand.

Unfortunately, I'm getting a "Maximum recursion depth exceeded" error with an unrelated line of code highlighted as the culprit.

![image](https://user-images.githubusercontent.com/5499519/83196471-f6771b80-a109-11ea-9d8f-94115ee5be02.png)

Replacing `itemSlots - 1` in `for i in range(0, itemSlots - 1)` to a simple `10` removes the error, so it leads me to believe the number of iterations is the cause. However, for my purposes, I need this number of iterations. Also, I've used this loop elsewhere in my code with the same terminating condition elsewhere, and it didn't complain. It seems to only let me use one or the other.

I've attached a copy of my code demonstrating the behavior.
[World Ends with You, The - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/4698396/World.Ends.with.You.The.-.Copy.rascript.txt)

**Comment by Jamiras** [comment]
It's the `never()` that's causing the issue. `never(A || B)` gets converted to `never(A) && never(B)`, and you're applying never to a chain of 400+ items. I'm not sure why that's being counted as recursive. Will continue to investigate.
