### ISSUE TITLE
never(repeated(N, X)) post-OrNext regression

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#167]
Loading my Soul Reaver script post-`OrNext` revealed a regression in which a previously supported logic pattern is no longer supported.

```
function was_attacked_by(index) {
    base = 0x1000
    return (byte(base + index + 0x11) == 0x11 && byte(base + index + 0x12) == 0x12) // attack 1
        || (byte(base + index + 0x21) == 0x21 && byte(base + index + 0x22) == 0x22) // attack 2
}

achievement("t", "d", 5,
    never(repeated(2, was_attacked_by(0) || was_attacked_by(1)))
)
```

This used to generate the following correct sequence of instructions:

![image](https://user-images.githubusercontent.com/623942/83942084-842cc800-a7e8-11ea-90cf-8603e674867f.png)

Now it results in an error: `Subclause is too complex`. Replacing the `repeated` with a `tally` did not make the error disappear. I tried like this:

```
never(tally(2, was_attacked_by(0), was_attacked_by(1)))
```

**Comment by Jamiras** [comment]
It's not really a regression. You're just not doing a full conversion to `tally`. Your expected results has four `tally` clauses: two generated by `was_attacked_by(0)` and two generated by `was_attacked_by(1)`. The `||` in the clause returned by `was_attacked_by` is what's triggering the error. You're effectively generating:
```
AndNext 0x1011 = 0x11
AddHits 0x1012 = 0x12
OrNext  0x1021 = 0x21
AddHits 0x1022 = 0x22
AndNext 0x1012 = 0x11
AddHits 0x1013 = 0x12
OrNext  0x1022 = 0x21
ResetIf 0x1023 = 0x22
```
Because `AndNext` and `OrNext` have the same priority, the final result is `(((A || B) && C) || D)`, when you wrote `(A || B) && (C || D)`, so the error is generated.

While this is definitely uglier code, the correct way to do the `tally` conversion to generate the original trigger is this:
```
function was_attacked_by(index) {
    base = 0x1000
    return [byte(base + index + 0x11) == 0x11 && byte(base + index + 0x12) == 0x12, // attack 1
            byte(base + index + 0x21) == 0x21 && byte(base + index + 0x22) == 0x22] // attack 2
}

clause = []
for i in range(0,1)
    for subclause in was_attacked_by(i)
        array_push(clause, subclause)

achievement("t", "d", 5,
    never(tally(2, clause))
)
```
You could clean it up a bit by refactoring `was_attacked_by`:
```
function build_attacked_by(clause, index) {
    base = 0x1000
    array_push(clause, byte(base + index + 0x11) == 0x11 && byte(base + index + 0x12) == 0x12) // attack 1
    array_push(clause, byte(base + index + 0x21) == 0x21 && byte(base + index + 0x22) == 0x22) // attack 2
}

clause = []
build_attacked_by(clause, 0)
build_attacked_by(clause, 1)

achievement("t", "d", 5,
    never(tally(2, clause))
)
```

**Comment by gdeOo** [comment]
You're right, it didn't occur to me that the inner `||`s  would have to flattened as well.

A bit inconvenient for composition unfortunately. The function needs to be aware of whether it'll be used in a normal logic context or in the context of a `tally`. This is already the case in other situations though, it's more of an issue with the toolkit.

Closing this.

----

A bit off-topic for the issue, but concerns the function having to be aware of its context:

Seems like most of these situations stem from the fact that the toolkit has no way to represent scope/nesting. Since every instruction is on the same level, even `OrNext` ends up being extremely limited. I really wish we could easily represent something like `(A || B) && (C || D)` without alt groups, `AddHits` or any other workarounds, regardless of whether `A-D` are single instructions or complex logical expressions.

It's one of the things that irks me the most when making achievements. Every time I use an `||` I'm forced to consider the context in which it'll be used, because there's no guarantee it'll just work, unlike `&&`s. I also end up avoiding them as much as possible to minimize code complexity/duplication. Even though I'm speaking in `RATools` terms, these are toolkit limitations and would apply to anyone coding in the achievement editor of course. It's weirder in `RATools` simply because the language is mostly designed around boolean logic, but then you have to deal with these practical limitations that force you to break the abstraction.

Have you ever considered this issue or maybe even a solution?

**Comment by Jamiras** [comment]
RATools tries to abstract the limitations of the toolkit. For example, #72 creates a cross product of the logic and generates all the necessary alts to cover all the possible combinations of logic.

As for expanding the toolkit itself - the only way to improve the functional grouping would be to change the Alt list into a tree where each node could define whether its children should be ANDed or ORd together. And I suspect something like that would not be easy to understand or use. Another approach might be to abstract subclauses into variables, and the variable could be used as a single element in an AndNext/OrNext chain (i.e. `F=A||B`, `G=C||D`, trigger=`F&&G`)

**Comment by gdeOo** [comment]
`RATools` does an excellent job at abstracting as much as possible, but some of the limitations just aren't bypassable.

I think the tree approach would be the best design. Besides having to initially adapt to it, I'm sure devs would come to love it. I don't think achievements are particularly easy to read as is, and a tree view would be a major improvement imo. Still, lots of changes here...

As for approaches that keep the status quo as much as possible, I agree that non-persistent variables could be a solution if implemented. It's not the prettiest one, but it'd be fine.

I have another possible approach, which is the one I always visualize when I think of this. It also doesn't disturb the status quo very much.

- The idea would be to allow conditions to be grouped, making them act as a single condition from the point of view of the preceding combining condition.
- Groups would be nestable to support complex logic expressions.
- Since a group is to be handled like a single condition, it would adopt the properties of its last condition (flag, hits, ...)
- My major doubt: what to do with flagged conditions inside groups. Obviously logic combining flags like `AndNext` and `OrNext` would be fine, but I don't think resets or pauses would be, If the group is to act as a single condition, it can't include multiple resets, for example. This doesn't seem like an insurmountable issue though. If nothing else, restricting the allowed flags would work.
- In terms of implementation, the grouped conditions could simply be wrapped in start- and end-group markers. For maximum compat the markers could even be empty conditions with a flag that is not exposed by the UI. The achievement editor could be tough to change in a way that displays the groups, but I'm sure it'd be doable.
