### ISSUE TITLE
OutOfMemoryException when ANDing groups of ORs

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#171]
I'm attempting to write a function that detects whether the player only has a sanctioned set of pins equipped. A player can have at most six pins equipped at a time, and the set of pins the player is allowed to use for the particular achievement I'm going for is relatively small (only about 30).

My algorithm simply iterates over a range of six integers, each representing a slot, and then I iterate over the entire list of allowed pins. So, for each slot, the player can have any of the sanctioned pins equipped, and this must hold true for all slots. The logic, then, is (P || P || P || P . . .) && (P || P || P || P || P . . . ) && . . . .

My attempt to do this, however, results in a peculiar OutOfMemoryException. I believe I've isolated the problem to a single line, and it is the line where I attempt to AND each OR subclause together. See below:

![image](https://user-images.githubusercontent.com/5499519/84586230-a1175b80-ade5-11ea-8b46-f2b20a706d53.png)

I've commented out the actual intended logic and replaced it with a line that ORs the subclause instead. This is incorrect logic, of course, but it provides a foil to compare and contrast performance.

I have also attached a copy of the code that demonstrates this behavior. 
[World Ends with You, The - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/4775940/World.Ends.with.You.The.-.Copy.rascript.txt)

It's very possible that the root cause is something completely different, but I'm at a loss as to what it could be or how it can be avoided.

**Comment by Jamiras** [comment]
The problem is expansion of `(P || P || P || P . . .) && (P || P || P || P || P . . . )`.

When you have `(A || B) && (C || D)`, that has to be expanded to `(A && C) || (A && D) || (B && C) || (B && D)` to fit into the Alt clause construct. You have 6 clauses with 19 conditions each, so the expansion is 19^6 (approximately 47 million) clauses.

For this specific use case, each clause is "word(X) == 0 || word(X) == 1 || word(X) == 2 ... word(X) == 17", so the clause could be collapsed to "word(X) <= 17" and the cross-product becomes much simpler.

I'm going to add an error message if the expansion would result it more than 10000 alts.

**Comment by MagmarFire** [comment]
Thank you for mentioning each clause being "word(X) == 0 || word(X) == 1 || word(X) == 2 ... word(X) == 17", because as it turns out, that's a bug with my implementation. In this use case, that should then make each clause "word(X) == 9 || word(X) == 53 || word(X) == 100 || word(X) == 101 ... word(X) == 272". Unfortunately, that does mean simply checking to see if it's less than 17 will not work, since the IDs could be any particular subset of the main set.

Mayhaps I should consider an alternative approach to this. That said, the error message will be very helpful if I encounter this particular thing again in the future.

**Comment by Jamiras** [comment]
```result = result && repeated(0, subclause)```
Does generate an OrNext sequence of reasonable size. I wonder if I can reasonably determine when to generate an OrNext chain instead of creating alts from the cross-product

**Comment by Jamiras** [comment]
If the cross-product of conditions would result in more than 20 alt groups, the code will now try to collapse some of the condition sets into OrNext chains. A condition set is considered collapsible if it only contains memory references and integer constants. Any `once()`, `repeated()`, `never()`, `unless()`, `measured()`, or user-defined function call will prevent the condition set from being collapsed.

After collapsing, the cross-product is recalculated. If more than 10000 alts are still generated, the error will be raised.
