### ISSUE TITLE
Dictionary key is not of a type error

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#173]
I'm creating dictionary objects and passing them to a custom function to create a certain achievement group via a loop. The schema for the dictionary is pretty simple--two fields expecting strings and two expecting integers.

In this case, the strings need to be generated via concatenation, and the integers need to be computed. When I attempt to do so, however, I get the following errors:

![image](https://user-images.githubusercontent.com/5499519/85158573-82242980-b22a-11ea-9265-34a8f499a112.png)

In this case, it refers specifically to the "threshold" value, and this disappears when I substitute a literal in its place. However, then other errors in the same vein show up for the other values, such as `title is not a string` or `description is not a string`. This is from the `achievement()` function itself being called from the wrapper, so it seems to not think that the values I'm passing to it are the right values. When I double check it, however, it 

When I substitute all the other values except the "name" value to eliminate possibilities, I still get the `title is not a string` error, even though all it is, is just a result of string concatenation:

`name = brand + "Enthusiast"`

Substituting all values with non-concatenated literals removes the error.

I have attached a version of the script that demonstrates the behavior. The intended code is on Line 1743, but I have a commented-out version of debug code that has literal substitutions. Uncommenting this and commenting out the other will remove the errors.

[World Ends with You, The - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/4805842/World.Ends.with.You.The.-.Copy.rascript.txt)

**Comment by Jamiras** [comment]
When passing the dictionary as a function parameter, the contents are not evaluated. Per the 1.6.6 release notes:
> arrays and dictionaries are no longer evaluated when passed to functions. this is significantly more
performant, and allows the function to modify the array/dictionary.

The contents of the dictionary are locally-scoped variables, so when they're pulled out of the dictionary and evaluated in the called function, the values cannot be found.

I'll look into forcing the evaluation of the dictionary when passing a dictionary not already in a variable.

This is a viable workaround:
```
    cheevo = {
        "name": name,
        "description": description,
        "threshold": 3,
        "points": 5
    }
    GenerateSaveProtectedAchievementFromConditions(cheevo, pinMasteryConditions)
```
