### ISSUE TITLE
"Combination of &&s and ||s is too complex for subclause" from automatically generated achievement dump

### ISSUE THREAD

**Issue by soopercool101** [Jamiras/RATools#179]
Test case:
https://retroachievements.org/achievement/116387 (Game ID: 14260)

**Comment by Jamiras** [comment]
`(A || B) && C` is being expanded to `(A && C) || (B && C)`, which cannot be properly represented using a chain of AndNext/OrNexts. It would work if the original expression was not expanded. I'll see if I can prevent the expansion when evaluating nested clauses.
