### ISSUE TITLE
Update unofficial/core entries directly

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#19]
If it is possible I would like to be able to import a set, make changes to it and push entries back to core/unofficial directly. Copying conditions from local is tedious when there are many alts, so it would make it easier to fix issues that require adding alt conditions (e.g. for cross-version compatibility).

**Comment by Jamiras** [comment]
This feature is supported by the newest release of raintegration, but not yet by RATools. After generating the user file, edit it and replace the 0 with the actual achievement ID. Note: This will continue to mark the achievement as modified each time the user file is loaded by the emulator, so change it back to a 0 or remove the line entirely after committing the changes.

**Comment by Jamiras** [comment]
This was included in 1.6.0 via #46
