### ISSUE TITLE
[Feature Request] Dump local achievements

### ISSUE THREAD

**Issue by soopercool101** [Jamiras/RATools#195]
Would be a useful tool to help those who might be more used to the standard achievement writing to learn the syntax, as well as help teach how to create some of the more complex functions.

(As an aside, is there a way to do Measured with Addsource in RATools? I couldn't figure out how to do so which is the main reason I want this feature myself)

**Comment by Jamiras** [comment]
> is there a way to do Measured with Addsource in RATools?

`measured()` just takes an expression. An `AddSource` expression is just the addition of two memory functions:
```
measured(byte(0x2345) + byte(0x1234) >= 32)
```
becomes
```
AddSource 8-bit 0x2345
Measured  8-bit 0x1234 >= 32
```
if you want to measure a hitcount, just include a `repeated`:
```
measured(repeated(16, byte(0x2345) + byte(0x1234) >= 32))
```
becomes
```
AddSource 8-bit 0x2345
Measured  8-bit 0x1234 >= 32 (16)
```
