### ISSUE TITLE
[feature request] add an option to "Update Local" more than one achievement

### ISSUE THREAD

**Issue by meleu** [Jamiras/RATools#2]
Currently we have to right-click one by one and then **Update Local**. There's no way to select all or even select some arbitrary cheevos.

It would be pretty handy.

Thanks.

**Comment by Jamiras** [comment]
I've added an `Update Local` item to the main menu. The dialog that opens allows selecting one or more items to commit to local. Initially, all modified items are selected.

**Comment by meleu** [comment]
Awesome! Will try it soon!

**Comment by meleu** [comment]
Just letting you know that this feature works fine. And the option to not generate cheevos in Local again is handy to not populate Local set repeatedly. Good catch!
