### ISSUE TITLE
Cannot generate trigger from IntegerConstant

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#20]
I am pretty sure that it is possible to define constant comparisons in the toolkit, so it should be supported here too, even if it rarely makes sense to use.

Example: `trigger = 0 == 0`.

**Comment by Jamiras** [comment]
You can use `always_true()` and `always_false()` to generate those: https://github.com/Jamiras/RATools/wiki/Script-File-Syntax#special-functions

**Comment by rzumer** [comment]
That's fine, but value comparisons are closer to the syntax in the toolkit, so it would be more intuitive to support that syntax.

**Comment by rzumer** [comment]
I found that sets with `1 == 1` core conditions are converted as-is and generate this error as well.
