### ISSUE TITLE
"Ambiguous logic clauses" when alts are already between parentheses

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#22]
I tried to simply copy and paste a trigger with `||` in the middle and parentheses around each group, and I am getting this error.

Even a trigger as simple as `(byte(0x0) == 0) || (byte(0x0) == 1)` will generate this error.

**Comment by Jamiras** [comment]
it's saying that is' ambiguous with the previous line:
`A & B || C`  => `(A & B) || C` or `A & (B || C)`

You either need more parenthesis: `((byte(0x0) == 0) || (byte(0x0) == 1))`
or less: `(byte(0x0) == 0 || byte(0x0) == 1)`

**Comment by rzumer** [comment]
The example I gave is exactly what is provided as the trigger. Adding or removing parentheses does not change the result in the editor.

**Comment by Jamiras** [comment]
That trigger as-is doesn't have a core group. That's probably confusing it. It should probably be enhanced to generate an `always_true()` core group in this scenario.

**Comment by rzumer** [comment]
That makes sense, adding a base condition does work. Thanks for the info.

**Comment by rzumer** [comment]
Note that the Script File Syntax page describes a usage of `always_false()` that will not work currently.

**Comment by rzumer** [comment]
I found that sets with `1 == 1` core conditions are converted as-is and generate errors as well.
