### ISSUE TITLE
{Enhancement] Find and Replace Function

### ISSUE THREAD

**Issue by SiouxerSkate** [Jamiras/RATools#220]
Would be handy to have a replace functionality added in with the find function. Something like ctrl + r would bring up the replace pane. 

Mainly thinking it would be a good efficient way to copy some cheevo logic when coding similar like achievements. That way you can find the old address and replace with new on multiple places.

**Comment by Jamiras** [comment]
Have you tried the existing functionality?
![image](https://user-images.githubusercontent.com/32680403/118208231-9c0ec200-b423-11eb-8a81-20bd01f2c516.png)

**Comment by SiouxerSkate** [comment]
HAHA didn't even see that!
