### ISSUE TITLE
[Enhancement] Optional function parameters for custom functions, or a `null` keyword

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#226]
As a developer, I want to be able to pass a null value to an optional function parameter, like `id` or `badge` for the `achievement()` function so that I can specify if an ID or badge exists in contexts where they're known for some achievements and don't yet exist for others.

In my scripts, I generally have a wrapper function that automatically generates a save-protected achievement given a few parameters, such as the conditions, the the number of conditions that must be true before the generated achievement triggers, etc. However, sometimes, these values--such as `id` and `badge`-- aren't known. This is typically when the achievements themselves are new. Whenever they are known, however, I can simply update the wrapper function to expect the new parameters. Since optional parameters don't seem to (yet) be supported, I've used dictionaries as substitutes, and those seem to work all right.

However, this becomes wonky when I'm adding new ones when older achievements exist in the same script. Since ID and badge would now be required at this point, there's no value that I know of that would be a good substitute for an ID, so I'd have to update the code in a very awkward fashion to check for the number of keys in the dictionary to differentiate when it's "new" versus when it's "old". It would be significantly easier if I could just do away with dictionaries in this case and just use optional parameters--or, at the very least, pass a `null` value that could be used if I want to pass a value to an optional parameter but treat it as if I didn't pass anything at all.

**Comment by Jamiras** [comment]
RATools has no concept of `null` or `Nothing` or whatever analog you want to use. The default parameters to `achievement` are as follows:
```
achievement(title, description, points, trigger, id=0, published="", modified="", badge="0")
```
I've updated the wiki to reflect this, as the previous description just indicated they were optional and not what their defaults actually were.

I've also added functionality to allow you to specify defaults for parameters in user-defined functions using the same syntax.
