### ISSUE TITLE
Editor crashes when performing certain actions (ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#23]
I had an error message pop up and the application subsequently crashed after a series of undo operations:
```
Unhandled ArgumentOutOfRangeException

Index and count must refer to a location within the string.
Parameter name: count
```

It seems easy to reproduce simply by making multiple small changes on different lines and trying to undo them all.

**Comment by Jamiras** [comment]
Yes. I know there's still a couple exceptions that occur in the editor, which is why the auto-save is overly aggressive. I have yet to track down steps to reproduce.

**Comment by rzumer** [comment]
Replacing the script from elsewhere in the editor (Ctrl+A -> Ctrl+V) also seems to do it.

**Comment by Jamiras** [comment]
I've been able to reproduce a crash-on-paste issue. The problem occurs when pasting a section of text over another section of text at the end of the file such that the number of lines decreases. The IndexOutOfRange exception occurs when trying to remove the selection from the lines that no longer exist.

Leaving open for the originally reported issue.

**Comment by rzumer** [comment]
I have also had it happen while reloading a file multiple times (through the Open dialog) as I was editing it externally. It does not happen consistently, but it may also be due to the number of lines decreasing.

**Comment by Jamiras** [comment]
I believe the two reported exceptions have been fixed. Please create a new issue if another exception is encountered.
