### ISSUE TITLE
[Bug] tally() doesn't always apply hit targets correctly

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#258]
I have an achievement, "Prime Sacrifice," where I want to determine whether or not a player has used any given combination of three different options available to them in battle and reset the achievement if the player happens to use all three. As such, it appears appropriate to wrap all individual options in a `once()` call so that none of them count multiple times and sum the total hit counts in a `tally()` call.

![image](https://user-images.githubusercontent.com/5499519/142141571-55cf9900-0f62-49f0-870f-74ea222f9349.png)

While this does correctly create an AddHits condition with a hit target of 1 for the first operand, it appears to completely ignore the rest of them.

![image](https://user-images.githubusercontent.com/5499519/142141759-c3fdc199-85d3-4abc-87cc-7ab10e2491ca.png)

It seems to me that `tally()` should respect the use of hit target setters like `once()` for each operand or to throw an error if this isn't supported, but it fails silently.

I have attached a version of the script that displays the behavior. Note that the script was written with the latest `master` version of RATools in mind, but I have confirmed that the seemingly-incorrect behavior is shown with the latest official version, after altering the script so that it compiles the achievement in question.

[Kingdom Hearts Birth by Sleep Final Mix - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/7552087/Kingdom.Hearts.Birth.by.Sleep.Final.Mix.-.Copy.rascript.txt)

**Comment by Jamiras** [comment]
`tally()` works just fine with individually hit-targetted conditions. The problem you're facing is an optimization error. The clause that's losing it's HitCount is effectively `once(always_false() || a > x && a < y)`, which gets converted to:
```
AndNext a > x
OrNext  a < y
        0 = 1 (1)
```
The optimizer sees the `OrNext 0 = 1` and discards the final condition without relocating the hit target, so the `once(always_false() || a > x && a < y)` clause becomes `a > x && a < y` and no hit count is captured when it is processed by the `tally()` code.
