### ISSUE TITLE
Unexpected behavior when chaining always_false() and always_true()

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#27]
While looking for a workaround to get similar functionality to the example usage of `always_false()` and alt building (i.e. have alts without a core condition), I noticed that the parser allows the following construction when setting a function local trigger variable (it does not seem to work for setting the trigger directly):

```
trigger = always_false() always_true()
```

This seems to set a core condition of `1 == 1` (`0 == 1` if the statements are swapped) and subsequently ORing this trigger will add alt conditions as desired.

When setting alts based on the `always_false()` example, as below, when using this construction as the base trigger condition the parser will not have any problem figuring out what to do, while just assigning the base value to `always_true()` will fail and generate an "ambiguous logic error".

```
trigger = always_false() always_true() // remove always_false() to test

for offset in [0, 1] {
    trigger = trigger || (
        (once(byte(0x0 + offset) == 10 - 2)) &&
        (byte(0x0 + offset) == 10 - 1) &&
        (once(byte(0x1 + offset) < prev(byte(0x1 + offset))) && byte(0x1 + offset) == 0)
    )
}
```

Since acts as a workaround for #22, it would be nice to fix this only when the `always_false()` plus ORs behavior is restored.

**Comment by rzumer** [comment]
Using this method in a different function yielded different results, and generated only a `1 == 1` core condition, while removing `always_true()` generated the error "No valid requirements found." as opposed to "Ambiguous logic clauses" as in this example. I don't really understand why. Here is the second function:

```
EXP = 0x0
STR = 0x1
HP = {
    "cur": 0x2,
    "max": 0x3
}

function item_quantity_trigger(target_item, target_quantity) {
    trigger = always_false() always_true()
    
    for offset in [0, 1] {
        trigger = trigger || (
            byte(target_item + offset) == target_quantity && once(byte(target_item + offset) == target_quantity - 1) &&
            never(byte(EXP + offset) != prev(byte(EXP + offset))) &&
            never(byte(STR + offset) != prev(byte(STR + offset))) &&
            never(byte(HP["max"] + offset) != prev(byte(HP["max"] + offset)))
        )
    }
}
```

**Comment by rzumer** [comment]
I am not sure if this is part of the same issue or a different one, but defining partial triggers in functions also seems to generate inconsistent behavior.

When defining a function returning `always_false() always_true()`, it tells me that I can only use `always_true()` in a trigger definition. If I give the function a body and assign that value to a variable (named `trigger`) and then return that, no problem, but later on I get the "ambiguous logic clause" error in the achievement trigger definition. So the only way to get this to work seems to be to define the initial partial trigger in the body of each individual trigger generation function.

**Comment by Jamiras** [comment]
You left out an important detail here:
```
function foo() {
    trigger = always_false() always_true() // remove always_false() to test

    for offset in [0, 1] {
        trigger = trigger || (
            (once(byte(0x0 + offset) == 10 - 2)) &&
            (byte(0x0 + offset) == 10 - 1) &&
            (once(byte(0x1 + offset) < prev(byte(0x1 + offset))) && byte(0x1 + offset) == 0)
        )
    }

    return trigger
}
achievement("Title", "Description", 5, foo())
```
This is a bug in the way the trigger is evaluated. The trigger keyword starts initializing a trigger, then each function call in the expression builds the trigger.

The correct way to write this is:
```
function foo() {
    trigger = always_false()

    for offset in [0, 1] {
        trigger = trigger || (
            (once(byte(0x0 + offset) == 10 - 2)) &&
            (byte(0x0 + offset) == 10 - 1) &&
            (once(byte(0x1 + offset) < prev(byte(0x1 + offset))) && byte(0x1 + offset) == 0)
        )
    }

    return always_true() && trigger
}
```
The "trigger" clause is a set of alts, and the `always_false()` condition will be optimized out. The `always_true()` condition is required so the trigger has a core group. You were defining the core group outside of the expression, but within the context of the trigger, so it just happened to work.

Standalone function calls inside a method called from a trigger should generate an error.

**Comment by rzumer** [comment]
I see, I will change my triggers to match this pattern, thanks.
