### ISSUE TITLE
"Update local" does not work when changing the script via pasting text

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#28]
It seems like changes are not detected when pasting into the editor and then selecting "Update local". However, after making a change such as removing an operator and writing it back into the editor window, a change is detected correctly and I can update again. I can't just change bit of text to get it to update, either, only operators have seemed to trigger an update.

**Comment by Jamiras** [comment]
Going to need better steps to reproduce. 

I was able to cut/paste entire `achievement` function calls, including a stopover in notepad to make modifications.

I was able to copy/paste addresses and variables from one achievement to another to change them, and copy/paste chunks of text in the title and description. In all cases, the item appeared modified and the right+click Update Local menu option was functional.

**Comment by rzumer** [comment]
```
function foo() {
    var = 10
    return byte(0x0123) == var
}

achievement("a", "b", 1, foo())
```

1. Paste in editor. The entry is created in the sidebar.
2. Change the value of `var` to 11.
3. Paste the whole script again, overwriting the contents of the editor. No change is detected.
![image](https://user-images.githubusercontent.com/7488362/54730376-f7eca180-4b5e-11e9-8ac4-348737ca9008.png)
4. Remove a closing parenthesis and add it again, or change an operator. The change is now reflected.
![image](https://user-images.githubusercontent.com/7488362/54730392-0fc42580-4b5f-11e9-9f04-ce9d15ead690.png)
