### ISSUE TITLE
Upgrade .net 4(windows) for .net 5(multiplataforma) or higher

### ISSUE THREAD

**Issue by WelingtonMonteiro** [Jamiras/RATools#282]
Upgrade from .net 4 (windows) to .net 5 or higher (multiplatform)
With this it is possible to compile and run the program on linux or mac systems without problems, without using wine, etc.

https://docs.microsoft.com/en-us/dotnet/core/install/linux#ubuntu

**Comment by WelingtonMonteiro** [comment]
How to Migrate from the .NET Framework to .NET 5 Controls:
https://www.grapecity.com/blogs/how-to-migrate-from-the-dot-net-framework-to-dot-net-5-controls

**Comment by Jamiras** [comment]
https://docs.microsoft.com/en-us/dotnet/core/porting/

RATools is heavily dependent on WPF:
> Both Windows Forms and WPF have been ported to .NET, but these remain Windows-only technologies.

There are also a handful of Windows-specific APIs being used. Most of which I suspect could be converted to something more generic, but it's still a manual process.
> if the library you're referencing is Windows-specific, such as a user32.dll or kernel32.dll, then the code only works on Windows.

-----

I see little benefit in being able to run RATools on Linux or Mac as the resulting `XXX-User.txt` file still has to be loaded into a Windows-only emulator. If you're already using WINE to run the emulators, it's not much of a stretch to also use WINE to run RATools.

However, as .NET Framework 4.6 reaches end of support this month, things are overdue for an upgrade (it's still on .NET Framework 4.0). Microsoft has not yet announced end of support for .NET Framework 4.8, but have announced that it's going to be the last .NET Framework release and everything with be .NET Core after that. It might be worth make the jump to .NET Core as part of the upgrade even if it doesn't enable Linux/Mac support. It seems like .NET 6.0 might be a good target as it was just released about six months ago and has LTS support (.NET 5.0 does not have LTS support), but it's not available in VS2019.

As a final note, RATools uses my shared tool library (Jamiras.Core.dll), and that would likely need to be converted/upgraded as well, which will impact all of the other projects I have that use that shared library.

**Comment by WelingtonMonteiro** [comment]
Good to know about this news, but yes I use emulators on linux without wine, and emulators already have linux support for a long time.
I'm trying to migrate here, in free time, if I can, I'll send you a PR, if I wanted to version!
But I will also be waiting! Thanks!!!

**Comment by Jamiras** [comment]
I've managed to upgrade the project to .NET Core 6.0, but it still has to be run in WINE because of the WPF dependency:
```
$ dotnet RATools.dll 
It was not possible to find any compatible framework version
The framework 'Microsoft.WindowsDesktop.App', version '6.0.0' (x64) was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.
...
```
There is not a linux distribution of `Microsoft.WindowsDesktop.App`, so I had to download the Windows version and install it via WINE to get the .NET Core 6 version of the application to run in Linux (still via WINE).

I have not tried to natively compile in Linux, but I suspect the same sort of issues will arise. As I noted above:
> Both Windows Forms and WPF have been ported to .NET, but these remain Windows-only technologies.

As such, I don't believe your original ask is possible without completely rewriting the WPF portions of the code.
> With this it is possible to compile and run the program on linux or mac systems without problems, without using wine, etc.

The other thing I've encountered is that the "AnyCPU" build only generates "AnyCPU" DLLs. The EXE that gets generated is still specifically x86 or x64. But since the EXE is just a bootloader for the DLL, which will get JIT'ed, I can provide both EXEs in a single distribution with the same DLLs and the user can run whichever is appropriate.

I still need to do some more testing. Despite the fact that this migration does not provide any tangible benefits, it's probably still a good thing to do for the long-run as the .NET Framework itself is deprecated and Microsoft is pushing .NET Core. Maybe the migration to .NET Core could be a stepping stone towards getting off WPF, but I don't expect that to happen any time soon.

**Comment by WelingtonMonteiro** [comment]
Congratulations, yes WPF is still dependent on windows, an alternative would be to use Electron for desktop, decoupling the ui from WPF.
But congratulations, as soon as I have a branch with .netCore6 available in both the core and the main project I will download it on my linux and test it.

**Comment by WelingtonMonteiro** [comment]
This condition is caused by the fact that your other machine may not have the required .NET 6 Desktop runtime to run your .NET 6.0 WPF app.

On the [official page to download .NET 6.0](https://dotnet.microsoft.com/download/dotnet/6.0), each SDK and related runtime version has its own notes. If you only install .NET 6.0 runtime, it won't install the related .NET 6.0 Desktop runtime to support WPF and Windows Forms.

For example:
![image](https://user-images.githubusercontent.com/4640319/163750925-e3ea8367-1d6f-4d94-b1ec-2abb4916eb27.png)

That picture shows that you still have to install .NET 6 Desktop Runtime manually after you install .NET 6 runtime.

Therefore to fix your problem, you have to install .NET 6 Desktop Runtime, not just installing .NET 6 Runtime.

**Comment by Jamiras** [comment]
I understand that. And on that very page you've linked, the download for the Desktop Runtime is ONLY AVAILABLE FOR WINDOWS.

![image](https://user-images.githubusercontent.com/32680403/163751532-e5713f0f-274d-46f2-b4d6-cea4a55d76bb.png)

And therefore, I had to download the WINDOWS installer, run it _through_ WINE and then use it _through_ WINE.

> There is not a linux distribution of Microsoft.WindowsDesktop.App, so I had to download the Windows version and install it via WINE to get the .NET Core 6 version of the application to run in Linux (still via WINE).

**Comment by WelingtonMonteiro** [comment]
True, I hadn't seen that part, so a future solution would be the decoupling of WPF using Electron for example.
Another option would be to use Blazor with MAUI, as I saw in this post in en: https://balta.io/blog/novidades-dotnet-6-preview-1.
But thanks for the intention, and I'll keep an eye on the next updates about the project
Thank you!

**Comment by WelingtonMonteiro** [comment]
Tanks :)
