### ISSUE TITLE
[feature request] make a shortcut for "Refresh Current"

### ISSUE THREAD

**Issue by meleu** [Jamiras/RATools#3]
It would be useful to invoke "Refresh Current" with a shortcut. What do you think about the F5 key?

**Comment by meleu** [comment]
Also, it would be useful if when performing a "Refresh Current" the RATools loaded Code Notes again. Sometimes the dev adds new Code Notes while the RATools is still running... ;-)

**Comment by Jamiras** [comment]
I've added a F5 keyboard shortcut for the "Refresh Current" menu item. 

It already does reload the Code Notes file, but the emulator doesn't update the file until the next time the game is loaded. To pick up the changes, you have to reload the game (or possibly restart the emulator).

**Comment by meleu** [comment]
your tool is awesome!
:heart:
