### ISSUE TITLE
[bug] Hardcoding 0 in rich_presence_lookup results in inoperable RP Script

### ISSUE THREAD

**Issue by wolfman2000** [Jamiras/RATools#312]
I admit that I like using emoji and other non-standard unicode characters in my RP Scripts. I think I found a situation where it breaks, though.

The first snippet is this:

```
RpUnicode = {
    0: "👮", // cop/lives
    1: "💯", // points/score
}
```

I wanted to try things this way because the built-in editor doesn't like me modifying lines with multi-byte characters in them.

After that, they went in relevant `rich_presence_lookup` functions:

```
RpLivesUnicode = rich_presence_lookup("Unicode", 0, RpUnicode)
RpScoreUnicode = rich_presence_lookup("Unicode", 1, RpUnicode)
```

From there, call `rich_presence_conditional_display` as per usual.

```
rich_presence_conditional_display(
    GsLeavingLevel || GsBonusAward,
    "Dread Is The Winner at {0} - {1}{2} {3}{4}",
    RpLevel,
    RpLivesUnicode,
    RpLives,
    RpScoreUnicode,
    RpScore
)
```

The generated rich presence for the above line is the following:

```
?1=1S0x 00fffe=29814S0x 00fffe=29824?Dread Is The Winner at @Stage(0xH0004a4) - @Unicode()@Number(0xH002b2f) @Unicode(v1)@Number(b0xH002b39*1000000_b0xH002b38*10000_b0xH002b3b*100_b0xH002b3a)
```

Note the lack of @Unicode(0) there. I get the following error when I try using this:

![image](https://user-images.githubusercontent.com/148345/168497797-1112ce52-76b6-44c1-9a65-950572c65ff3.png)

I'm hoping there is a way to make things work for the values 0 and 1.

**Comment by Jamiras** [comment]
The value "1" does work. The issue with "0" is that it's trying to optimize out a "+0", leaving the final result as empty string.
