### ISSUE TITLE
Cannot Create Script for Wario Land II (Game Boy Color)

### ISSUE THREAD

**Issue by wolfman2000** [Jamiras/RATools#315]
For some reason, any time I try to create a new script based off of Game ID 14221 (Wario Land II), it crashes on me and never generates. I'm unsure if something is off on my end.

**Comment by wolfman2000** [comment]
I've identified a possible source for the issue. Prior to creating the script, I created a local leaderboard for testing purposes. I think it's failing to parse that leaderboard for some reason.

**Comment by Jamiras** [comment]
As you've surmised, the problem is the local leaderboard. There was an uninitialized variable when the leaderboard entry was being created for the New Script dialog (instead of the main editor).
