### ISSUE TITLE
Importing Add Hits (tally) achievements made in the RAIntegration editor to an RAScript using RATools

### ISSUE THREAD

**Issue by timenoe** [Jamiras/RATools#318]
[19097-User.txt](https://github.com/Jamiras/RATools/files/8829123/19097-User.txt)

I have attached my local 19097-User.txt with two achievements where the problem occurs. Also, I made clones of the achievements to remove the measured that is attached to the tally, but the same results occurred.

Here is the first example: 
![image](https://user-images.githubusercontent.com/62894028/171776775-a5126937-bc68-4fea-9204-7efb0cbb5479.png)

First, on line 16, it should be "0x00612) == 0", but the 0 was not included. Also, there is an extra parenthesis on line 17.

Here is another similar example:
![image](https://user-images.githubusercontent.com/62894028/171776996-984b4d20-ff6b-4d25-a765-33a80d58d71d.png)

On line 34, there is an extra parenthesis, just like the first example.

**Comment by Jamiras** [comment]
The problem is occurring when it changes the `repeated(8, ...)` into a `tally(8, ...)`. It's trying to find and remove the `always_false()`, but instead it's removing the `0` because of the `when` subclause.
