### ISSUE TITLE
Automatic optimization

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#32]
There are a few things that could be optimized when "compiling" to the target format. It is probably very low priority right now but I wanted to keep track of a situations that come to mind for now. There should probably be multiple levels of optimization, or at least on "level" turned on at all times that gets rid of superfluous conditions and another toggleable that can reduce the number of conditions at the possible cost of readability.

Always optimize:
- Remove "always true" conditions (except for core groups with only one condition) (i.e. mem == mem, delta == delta, value == value where the parameter is the same)
  - `always_true() && [non-always-true conditions]` does not always optimize away `1 == 1`
- ~Remove duplicate conditions~
  - inc. when operands are swapped
  - ~inc. in alts when the condition is in core~
  - inc. duplicates with differing hit counts (prioritize the lower hit count condition?)
- ~Move identical conditions present in every alt to core~
- Only reset/never() and pause/unless() conditions -> regular conditions with inverted operators

Possibly optimize:
- ~Consolidate comparisons with the same operand (mem/delta/value) if they span a larger accessor's range (e.g. consolidate bit0\~3 checks in one address to lower4, individual consecutive bytes to 16\~32 bits, etc.)~
- Remove superfluous `ResetIf` (`never()`)/~`PauseIf` (`unless()`)~ statements when there is no hit check and invert the comparison operators
  - are there situations where they are distinct from standard comparisons despite no hit checks being there?

I will edit this post if I can think of anything else.

**Comment by Jamiras** [comment]
Several of these things should already be occurring:
* duplicate conditions: https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L353
  - does not handle swapped operands
* promoting common alt conditions to core: https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L340
* remove conditions in alts that are already in core: https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L412
* remove unless() if no hits: https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L333
* merge bits into lower/upper/byte: https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L415
   - does not merge consecutive bytes to 16-bit or 32-bit - this is typically undesirable as bytes have separate code notes

**Comment by rzumer** [comment]
Great, I stroke out those that are done already from my understanding (if I missed one feel free to edit my post).

**Comment by Jamiras** [comment]
> always_true() && [non-always-true conditions] does not always optimize away 1 == 1

Can you give an example for this? I believe it's addressed by these unit tests:
https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L351
https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L388-L389

> Only reset/never() and pause/unless() conditions -> regular conditions with inverted operators

If I understand the request, that's handled by these unit tests:
https://github.com/Jamiras/RATools/blob/master/Tests/Parser/AchievementBuilderTests.cs#L355-L370

And how is this different from that?

> Remove superfluous ResetIf (never())/PauseIf (unless()) statements when there is no hit check and invert the comparison operators

I believe that with the changes in #88, all of the bullets are now covered.

**Comment by rzumer** [comment]
>Can you give an example for this? I believe it's addressed by these unit tests:

Seems like it. There might be some corner case that I hit earlier, but I don't have samples saved, so I can reopen an issue if I notice this happening again.

>And how is this different from that?

The "only".

I think it is fine to close with #88.
