### ISSUE TITLE
SubSource is not parsed correctly in the achievement view

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#33]
The output for SubSource is correct, but when viewing the logic in the achievement view, it is not. This might also affect AddSource and other recent additions.

Example of SubSource use:

Source:

```
trigger = STAGE - prev(STAGE) == 1
```

Output:

![image](https://user-images.githubusercontent.com/7488362/52904318-3279bc00-31f8-11e9-8fba-ce992f8a1d17.png)

I would expect `byte(0x005B41)` prior to the minus sign, but instead the accessor is omitted and the address is appended to the code note, followed by a colon.

**Comment by Jamiras** [comment]
The display may be awkward, but it reflects the actual generated logic.
`- prev(byte(0x005B41))` => `SubSource Delta 8-bit 0x5B41`
`byte(0x005B41) == 1` => `Mem 8-bit 0x5B41`

However, the address should only be prefixed on the note when comparing two different addresses in a single condition. I've fixed that, and modified the line to display `-prev(byte(0x005B41)) +`

**Comment by rzumer** [comment]
OK, seems good to me.
