### ISSUE TITLE
Loading a script not associated to a local user file and selecting "Update local" crashes

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#35]
Greying out the option or displaying an error message and failing gracefully would be better.

**Comment by Jamiras** [comment]
Please clarify steps. If I delete the "XXX-User.txt" file, both the menu option and the right click option recreate it. If I remove the "// #ID" line, the script won't load with a "could not find Game ID" error.

**Comment by rzumer** [comment]
The ID exists but the platform it is associated with does not have a data directory set up in the configuration.
