### ISSUE TITLE
[Bug] Autogenerated achievement comes with "Never not allowed in subclause" error.

### ISSUE THREAD

**Issue by Ben-Ghazi** [Jamiras/RATools#355]
When trying to generate a script for this achievement: https://retroachievements.org/achievement/268631 I get an output that looks like this:
![Screenshot 2022-11-22 150535](https://user-images.githubusercontent.com/39404689/203421217-ec59365a-6148-4267-b635-5a9bded885a7.png)

The issue persists even on the core achievement which has several conditions removed. I'm using the 1.10.0 64-bit version of RATools.

**Comment by Jamiras** [comment]
There's a set of parentheses missing around the OR'd conditions:
```
     ((once(((dword(0x0778D8) != 47155 && byte(0x077FD0) < prev(byte(0x077FD0))) || byte(0x0757F8) == 6) &&
        never(prev(byte(0x078BBC)) != 255 && byte(0x078BBC) < prev(byte(0x078BBC)))) && byte(0x075964) == 10 && 
```
