### ISSUE TITLE
Output condition set sometimes cannot be parsed correctly by the toolkit

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#36]
Source:
```
// ...

function my_trigger()
{
    return byte(0x123) == 0 &&
        once(byte(0x123) > 0) &&
        never(!my_func()) &&
        never(prev(byte(0x456)) != byte(0x456)) &&
        never(prev(byte(0x123)) < byte(0x123))
}

// ...

achievement
(
    title = "My title", description = "My description", points = 1,
    id = 123, badge = "456", published = "2019-01-22 15:40:36", modified = "2019-01-22 15:40:36",
    trigger = my_trigger()
)
```

For some reason the result is a new local entry with the defined description as the title, the points as the author, and an empty condition set. I have seen this occur twice, including with this example.

It seems dependent on the order of conditions.

**Comment by Jamiras** [comment]
What is "my_func"? i had to comment that line out, and it seems to work as expected without it.

The shifting suggests an incomplete condition was output, resulting in the title being consumed as part of the trigger.

**Comment by rzumer** [comment]
```
function my_func() => byte(0x567) == 2
```

I made some changes to my reference script to simplify it. I had another example but cannot seem to reproduce it now. If I can find another I will post it in a new comment.

**Comment by rzumer** [comment]
Here is another example.

I have a boilerplate function for single bit flag checks. With the part that adjusts the address and bit values if the given bit is larger or equal to 8, calling this function as part of a trigger (with a bit value of 8 or more) causes this to happen, even though the code seems to be interpreted correctly in the achievement view.

```
function single_bit_trigger(target_addr, target_bit) {
    actual_addr = target_addr
    actual_bit = target_bit

    if target_bit >= 8 {
        for i in range(8, target_bit, 8) {
            actual_addr = actual_addr + 1
            actual_bit = actual_bit - 8
        }
    }

    if actual_bit == 0 {
        trigger = bit0(actual_addr) > prev(bit0(actual_addr))
    } else {
        trigger = bit0(actual_addr) == prev(bit0(actual_addr))
    }

    if actual_bit == 1 {
        trigger = trigger && bit1(actual_addr) > prev(bit1(actual_addr))
    } else {
        trigger = trigger && bit1(actual_addr) == prev(bit1(actual_addr))
    }

    if actual_bit == 2 {
        trigger = trigger && bit2(actual_addr) > prev(bit2(actual_addr))
    } else {
        trigger = trigger && bit2(actual_addr) == prev(bit2(actual_addr))
    }

    if actual_bit == 3 {
        trigger = trigger && bit3(actual_addr) > prev(bit3(actual_addr))
    } else {
        trigger = trigger && bit3(actual_addr) == prev(bit3(actual_addr))
    }

    if actual_bit == 4 {
        trigger = trigger && bit4(actual_addr) > prev(bit4(actual_addr))
    } else {
        trigger = trigger && bit4(actual_addr) == prev(bit4(actual_addr))
    }

    if actual_bit == 5 {
        trigger = trigger && bit5(actual_addr) > prev(bit5(actual_addr))
    } else {
        trigger = trigger && bit5(actual_addr) == prev(bit5(actual_addr))
    }

    if actual_bit == 6 {
        trigger = trigger && bit6(actual_addr) > prev(bit6(actual_addr))
    } else {
        trigger = trigger && bit6(actual_addr) == prev(bit6(actual_addr))
    }

    if actual_bit == 7 {
        trigger = trigger && bit7(actual_addr) > prev(bit7(actual_addr))
    } else {
        trigger = trigger && bit7(actual_addr) == prev(bit7(actual_addr))
    }

    return trigger
}
```

**Comment by rzumer** [comment]
I think that it is an error in the toolkit, actually.

The following is the serialized output for the third entry pasted above.

```
0:0xH045adc=22_d0xH045adc=22S0xM045cc8=d0xM045cc8_0xN045cc8=d0xN045cc8_0xO045cc8=d0xO045cc8_0xP045cc8=d0xP045cc8_0xQ045cc8=d0xQ045cc8_0xR045cc8=d0xR045cc8_0xS045cc8=d0xS045cc8_0xT045cc8>d0xT045cc8S0xM045cc9=d0xM045cc9_0xN045cc9=d0xN045cc9_0xO045cc9=d0xO045cc9_0xP045cc9>d0xP045cc9_0xQ045cc9=d0xQ045cc9_0xR045cc9=d0xR045cc9_0xS045cc9=d0xS045cc9_0xT045cc9=d0xT045cc9S0xM045cc9=d0xM045cc9_0xN045cc9=d0xN045cc9_0xO045cc9=d0xO045cc9_0xP045cc9=d0xP045cc9_0xQ045cc9=d0xQ045cc9_0xR045cc9=d0xR045cc9_0xS045cc9=d0xS045cc9_0xT045cc9>d0xT045cc9S0xM045cca=d0xM045cca_0xN045cca=d0xN045cca_0xO045cca=d0xO045cca_0xP045cca>d0xP045cca_0xQ045cca=d0xQ045cca_0xR045cca=d0xR045cca_0xS045cca=d0xS045cca_0xT045cca=d0xT045cca:foo:bar: : : :Me:10:0:0:0:0:0
```

**Comment by Jamiras** [comment]
> As-is, it does not parse correctly in the toolkit. But add a value comparison at the end, such as _0=1, and it works.

This is a bug in the toolkit. With the rcheevos integration, the local trigger is not actually processed as its read. Instead, we look for a colon not following one of "abcpr" (add source, sub source, add hits, pauseif, resetif). Because the last clause in the trigger is an address ending in 'a', the separator that's 
supposed to be between the trigger and the title is assumed to be part of an add source and the title is consumed as part of the trigger, which then causes an error when rcheevos tries to parse it. The solution is to wrap the trigger in quotes, which is illustrated by the output from the toolkit. This sounds like the original issue (fields are off by one).

I've modified RATools to also output quotes when it generates local achievements. This will also allow the use of colons in titles and descriptions.

Let me know if you see the issue again.
