### ISSUE TITLE
Empty output when combining some operations?

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#37]
I think it is related to `SubSource`.

Example function:

```
LEVEL = byte(0x123)

function level_up_trigger(target_level) {
    trigger = LEVEL - prev(LEVEL) == 1

    if target_level > 0 {
        trigger = trigger && LEVEL == target_level
    }

    return trigger
}
```

The result when calling `level_up_trigger()` with a `target_level` above 1, it seems, is an empty condition set.

**Comment by Jamiras** [comment]
Please clarify. If I call with "2", it generates this: `B:0xH000123=0_d0xH000123=1_0xH000123=2`, which is not an empty condition, but is wrong. It should generate: `B:d0xH000123=_0xH000123=1_0xH000123=2` (the delta should be on the SubSource expression).

**Comment by Jamiras** [comment]
The problem is that the generated code is:
```
SubSource prev(byte(0x123))
          byte(0x123) == 1
          byte(0x123) == 2
```
It sees the "byte(0x123) == 1" and "byte(0x123) == 2" as conflicting and nulls out the group.
