### ISSUE TITLE
Application crash when leaderboard is empty

### ISSUE THREAD

**Issue by drisc** [Jamiras/RATools#375]
Trying to load from RACache with an empty leaderboard causes a NullReferenceException.

Example:
![image](https://user-images.githubusercontent.com/2449110/212568766-45142cb9-9543-4afc-8085-871c85893986.png)

**Comment by Tsearo** [comment]
Discussing in #jr-dev - https://discord.com/channels/310192285306454017/533411674162593812/1064293968151593011

Leaderboard causing the issue (deleting it resolved the error)
![image](https://user-images.githubusercontent.com/4047771/212568917-fe18bd60-f086-46d2-b3d4-f64bf169f943.png)
