### ISSUE TITLE
[Bug] An AND'd and OR'd clause nested within never() that is nested within a repeated() results in multiple Reset Next Ifs

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#379]
I have an achievement where I need to keep track of however many times the player used a particular Summon in a row, so as to prevent them from using the same one multiple times in a row. To do this, I have the following functionality (please ignore the commented code):

![image](https://user-images.githubusercontent.com/5499519/215628446-c2b2f4c5-503d-4257-a621-0bdd1054696e.png)

The idea is that, for each Summon, I check to see if the player used that Summon to increase a hit counter. If the player reaches 2, then the achievement is reset. If the player uses a Summon different from the Summon I'm looking at, the Reset If hit target is reset.

I expect the resulting hit-resetting code to look something like the following:

![image](https://user-images.githubusercontent.com/5499519/215628972-faca3408-fee3-49da-b94a-c956135bd372.png)

However, what actually ends up being generated is the following:

![image](https://user-images.githubusercontent.com/5499519/215629207-4f20a157-9edf-4d7c-8577-14de9026c762.png)

Since Reset Next If is a flag that in and of itself ends a Reset Next If chain, only the last Reset Next If will actually reset the relevant hit target.

I have attached a version of the script that demonstrates the behavior.

[Kingdom Hearts II Final Mix.rascript.txt](https://github.com/Jamiras/RATools/files/10541221/Kingdom.Hearts.II.Final.Mix.rascript.txt)

**Comment by Jamiras** [comment]
You're right. The second image is incorrect. A ResetNextIf will reset all hits until it encounters something that's not an AddAddress, AddSource, SubSource, AndNext or OrNext, so it will stop at the next ResetNextIf.

However, I don't believe your first image is correct either. The AndNext/OrNext chain is sequential. The logic in your first image is:
`ResetNextIf(((((A == 2 && D == 0) || A == 3) && D == 0) || A == 4) && D == 0)`

I think what you really want is:
`ResetNextIf((A == 2 || A == 3 || A == 4) && D == 0)`

```
OrNext      A = 2
OrNext      A = 3
AndNext     A = 4
ResetNextIf D = 0
```

**Comment by Jamiras** [comment]
I've updated the code to not split the never() clause into several ResetNextIfs, and the optimizer is able to successfully eliminate the duplicate `delta() == 0` checks.
