### ISSUE TITLE
Leaderboard - Unable to add AndNext or OrNext to Value parameter

### ISSUE THREAD

**Issue by BacklogOdyssey** [Jamiras/RATools#396]
While creating a measured value condition for a leaderboard, I get an error stating I'm unable to add more than one logical clause to a measured comparison and then RATools crashes with an index out of range exception. Basically, I need to add an AddNext to the measured comparison, but I'm unable to. Below is an example of what I'm trying:

value = measured(gameState() == 0x42 && prev(collectedCds()) < collectedCds())

Here's a screenshot of what the logic looks like in the RALibRetro Leaderboard Editor:

![image](https://github.com/Jamiras/RATools/assets/82419212/5c88af90-2951-4296-8098-b6b1cb090df9)

Thanks for the help and let me know if you need any additional information!

**Comment by Jamiras** [comment]
You want to use an [unbounded tally](https://github.com/Jamiras/RATools/wiki/Trigger-Functions#tallycount-comparisons), which reflects the intent to count hits:
```
value = measured(tally(0, gameState() == 0x42 && prev(collectedCds()) < collectedCds()))
```

I'll see if I can improve the error.

**Comment by BacklogOdyssey** [comment]
Worked like a charm! Thanks so much.
