### ISSUE TITLE
[Feature Request] trigger_when() ResetNextIf condition

### ISSUE THREAD

**Issue by TwosomesUP** [Jamiras/RATools#404]
In situations where a trigger has a stored hit count, it would be great to be able to reset that count with a ResetNextIf. A good example would be counting the number of times a player hits an enemy with a particular attack during an enemy's vulnerable state, and resetting it when that enemy's state changes to an invulnerable one. Basically challenging the player to hit the enemy a target amount of times before the enemy become invulnerable:

![image](https://github.com/Jamiras/RATools/assets/137419624/91271be1-31ef-4667-bbd2-3fc6e4b7c871)

**Comment by Jamiras** [comment]
This should already be present. Just put the `never()` inside the `trigger_when()`.

```
achievement("Test", "Test", 5,
    once(byte(0x1234) == 1) &&
    trigger_when(
        repeated(3, prev(byte(0xc605)) > byte(0xc605) && byte(0xc101) == 1) &&
        never(byte(0xc020) == 1)
    )
)
```
![image](https://github.com/Jamiras/RATools/assets/32680403/d0ebf892-86cc-4433-8d1e-351dc95cbc03)

Note that the additional `once()` outside the `trigger_when()` is necessary to keep the `Reset Next If` from being turned into a `Reset If`.

**Comment by TwosomesUP** [comment]
Perfect! Had to rework the logic a bit to fit the once() in, but worked like a charm.

**Comment by Jamiras** [comment]
You shouldn't _need_ to fit the `once()` in. If the only hit count in the list is in the trigger, the `Reset Next If` can safely be turned into a `Reset If`. That's just the optimizer choosing a more compatible behavior (RetroArch versions older than 1.9.4 don't support `Reset Next If`).

**Comment by TwosomesUP** [comment]
The biggest issue I was running into with the ResetIf, was the challenge indicator dropping when 0xc101 was equal to 0x01. It cycles between a few different values during the session. The ResetNextIf keeps it on screen during the entirety of the challenge. That said, I could probably just drop the trigger_when() as well haha

Thanks again for the help!

**Comment by Jamiras** [comment]
Ah, yes. The `Reset If` would cause the other non-trigger conditions to be false, and the challenge indicator would disappear. I'll see if I can't force it to keep the `Reset Next If` when used in a `trigger_when`.

**Comment by BacklogOdyssey** [comment]
Awesome! Truly appreciate your work on this, RATools has been a life saver. 😆
