### ISSUE TITLE
Centisecs vs Centiseconds

### ISSUE THREAD

**Issue by BoomEX-UK** [Jamiras/RATools#410]
https://github.com/Jamiras/RATools/blob/e0ed085c226b42d5efa58b40c7555c85b6cfcb65/Tests/Parser/Functions/RichPresenceMacroFunctionTests.cs#L58

I was looking for `Centiseconds ` but couldn't find it in RATools - I have found a reference to `Centisecs` but RALibretro shows `Unknown Macro` when using it

**Comment by Jamiras** [comment]
That's a transposition error. https://github.com/RetroAchievements/rcheevos/pull/160 says "Centisecs" in the description, but implemented it as "Centiseconds". It also implemented a "SecondsAsMinutes" macro that wasn't described, and therefore not exposed in RATools.
