### ISSUE TITLE
Crash when creating or loading a script

### ISSUE THREAD

**Issue by PopovMark** [Jamiras/RATools#442]
RATools crashes when creating a new script (New Script -> Search button -> crash) or loading an existing one (Recent list or file dialog, doesn't matter). This will happen for any game that has existing stuff in the emulator's RACache folder and does not throw a "no code notes found" popup. RATools freezes up and silently closes itself. The logs show this:

`14:14:47.242 GEN Showing NewScriptDialogViewModel dialog: New Script`

which I assume is just for opening the menu with the button, not the actual crashing bit.
No relation to specific game numbers, I used 669 to test (Link's Awakening GB).

**System: Windows 10 64-bit
Emulator: RALibretro 1.7
RATools version: 1.12.2 (Latest as of this writing)**

**Tried the following:**

- Running RATools with admin rights (no effect)
- Changing username/web API key in the settings (no effect)
- Clearing out the game's RACache files (loading an existing script will work; if you load the game in the emulator again, RACache files will be created and a subsequent attempt to open the script will cause a crash)
- Removing the emulator directories in RATools (standard behavior, will keep behaving as if there's nowhere to load the notes from)
- Changing the emulator directory (changed to root of D: drive, no effect)
- Opening a random text file with no game header (works fine)
- Opening a text file with only the header and nothing else (no effect, will crash if RACache files are present)
- Freshly reinstalling both RATools and RALibretro (no effect).

**Comment by Jamiras** [comment]
When it crashes, is it reporting an exception? Perhaps "Input string was not in the correct format"?

If so, are you running on a system where the locale settings uses a comma for decimal values (i.e. `pi=3,14`)?

**Comment by PopovMark** [comment]
No, it doesn't show anything. Nothing on the screen, nothing in the logs.
My system is in Russian language and has the appropriate locale (commas for decimal values), but I don't see how that affects anything because it worked fine before.

**Comment by Jamiras** [comment]
There was a change to the data being received from the server where it has decimal values now and didn't before. If your local expects commas for decimal values, it would cause an "Input string was not in the correct format" error trying to parse the server data. That was fixed by https://github.com/Jamiras/Core/pull/32 and will be included in the next release.

**Comment by PopovMark** [comment]
Yeah, but then where and when is the error message supposed to show up? I already told you it doesn't show anything for me.

**Comment by Jamiras** [comment]
It would happen when doing a new script, or loading an existing script for "any game that has existing stuff in the emulator's RACache folder".

I don't see the problem on 1.12.2:
![image](https://github.com/Jamiras/RATools/assets/32680403/86ce217c-31d5-4076-a491-59096cdcad64)

You've already stated that you are on a machine where the locale uses commas, so I'm pretty confident it's the same issue. Can you drop the DLL referenced [here](https://discord.com/channels/310192285306454017/936655398725902356/1198735303893069834) into your installation and see if it fixes the problem?

**Comment by PopovMark** [comment]
Looks like that fixes it, thank you very much dude!
