### ISSUE TITLE
Unresolved identifiers cause triggers within functions to be silently disposed instead of generating an error

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#48]
Here is an example trigger function body:
```
function clear_area_trigger(area_offset, is_immortal) {
        return AREA == area_offset && prev(AREA) == area_offset &&
            single_bit_trigger(DUNGEON_CLEARED_FLAGS, area_offset) &&
            byte(I_AREA_RANKS + offset) < 10 && prev(byte(I_AREA_RANKS + offset)) == 10
}
```

Later assigned to a trigger along with a couple of other conditions.

It is probably reducible to a simpler form.

In this case I wrote `offset` instead of `area_offset` on the bottom line, and the script managed to compile regardless, but completely ignored the function in the generated code.

**Comment by rzumer** [comment]
Another example is inside a branch within a function. Example:
```
function foo(param) {
    trigger = always_true()

    if param == 0 {
        trigger = byte(0x123) == 1
    } else {
        trigger = byte(0x123) == 1 && UNDEFINED_VAR == 0
    }
}
```

Instead of an error, the trigger remains in its default state.

**Comment by Jamiras** [comment]
I was unable to reproduce using the first example. In 1.5.4, the trigger is underlined with the error "Unknown variable: offset". In master, `offset` itself is underlined with the same error.

I was able to reproduce using the second example. Errors within an if statement were being swallowed.

**Comment by rzumer** [comment]
In the first example I thought I had pasted the full thing, but I guess I forgot about the important `if` block (the final version of that function is conditional); sorry about that.
