### ISSUE TITLE
Multiple Measured% rejected by RATools

### ISSUE THREAD

**Issue by GauChoob** [Jamiras/RATools#496]
I have an achievement that uses multiple Measured Alt Groups to handle different situations. Each Measured condition has the same target value of 50. The achievement works as expected.

However, when I add `format = "percent"`, I get the error: "Multiple measured() conditions must have the same target". I get this error even if I add the `percent` parameter to all of the Measured conditions, which is not what is expected.

If I export the achievement to RALibRetro, and manually checkmark Measured% in RALibRetro, the achievement works as expected for all AltGroups.

To reproduce this error:
Open up RA Tools
Import Game ID 13941 and Import the following Test achievement: https://retroachievements.org/achievement/436990

You will see that although the achievement is correctly imported, after being imported, it immediately throws the above error.

This issue is present on 1.14.0

**Comment by Jamiras** [comment]
The problem is that the optimizer is moving the explicit `-90` on the first alt and the `-789` on the third alt to the right side:
```
measured((word(0x04437C) - 90 - byte(0x044376) * 10) == 50)
measured((word(0x04437C) + 96 - byte(0x044376) * 16) == 50)
measured((word(0x04437C) - 789 - byte(0x044376)) == 50)
```
becomes:
```
measured((word(0x04437C) - byte(0x044376) * 10) == 140)
measured((word(0x04437C) + 96 - byte(0x044376) * 16) == 50)
measured((word(0x04437C) - byte(0x044376)) == 839)
```
and then the target values do differ.

I'll probably have to make the optimizer not do that particular change if encapsulated within a `measured()`. When the programmer specifies a target value, that's the value that should be displayed in the measured bar.

**Comment by GauChoob** [comment]
That makes sense, even for a single MeasuredIf, the constant values probably should not be optimized, since it would affect the measured percentage value (e.g. for the first measured clause of the above example, 0/50 = 0% vs 90/140 = 64%)

Thanks for your incredible work in maintaing RATools and everything else you do!
