### ISSUE TITLE
[feature request] builtin editor

### ISSUE THREAD

**Issue by meleu** [Jamiras/RATools#5]
I'm really happy with the current RATools features. My productivity in coding achievements is like, WOW!, much much much faster.

A builtin editor is not a high priority feature, but it would be cool to have it at some point.

Thanks.

**Comment by Jamiras** [comment]
I agree. I'd like to have something with syntax highlighted and auto-completion, but it's very difficult to create a functional rich text editor.

**Comment by rzumer** [comment]
I started working on a basic [VS Code extension](https://marketplace.visualstudio.com/items?itemName=rzumer.rascript-vscode) with language support for RAScript. Besides the built-in hinting in VS Code, it supports bracket auto-closing, snippets and basic syntax highlighting. It's not much, but it might help with readability during development.

**Comment by Jamiras** [comment]
Should be addressed by #14
