### ISSUE TITLE
Trailing newlines are appended unnecessarily

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#50]
Whenever I save a file, an additional line gets appended to the bottom. It is a minor issue, but it can get annoying to constantly trim the end of a file after working with it.

**Comment by Jamiras** [comment]
I'm unable to reproduce. The save code is here: https://github.com/Jamiras/RATools/blob/master/ViewModels/ScriptViewModel.cs#L87-L91

Each visible editor line is flushed one-at-a-time to the file. Calling `WriteLine` appends a newline at the end of each line, so the last line in the editor will have a trailing newline character.

Lines are separated by splitting on '\n': https://github.com/Jamiras/RATools/blob/master/ViewModels/ScriptViewModel.cs#L87-L91

So unless there's something after that last newline, there shouldn't be an "extra" line being generated by the read code, which would be required for an extra line to be output by the write code.

**Comment by rzumer** [comment]
I was definitely wrong about the behavior. What seems to happen is that trailing newlines in loaded files are not displayed in the editor, but are maintained when saving. So when using the editor on its own there is no issue, but when pasting from an external editor (I mostly use VS Code) any trailing newline *is* pasted in, and an extra newline is added when saving from the editor. Since VS Code refreshes file contents when they are saved externally, when making changes between the two editors and replacing the full file contents in RA Tools, the extra trailing lines pile up.
