### ISSUE TITLE
Issue with Add Address + Sub Source Delta

### ISSUE THREAD

**Issue by TwosomesUP** [Jamiras/RATools#505]
In RATools I'm trying to detect when a 32-bit BCD score increases by a specific amount, however when the logic for the below script is generated, the Sub Source lines seem to be dropping the "Multiply by" value.

Sample Script:
```
Player = {
"Score": (
        low4(Pointers["Score"] + Offsets["Score"][2]) * 100 +
        high4(Pointers["Score"] + Offsets["Score"][3]) * 1000 +
        low4(Pointers["Score"] + Offsets["Score"][4]) * 10000 +
        high4(Pointers["Score"] + Offsets["Score"][5]) * 100000 +
        low4(Pointers["Score"] + Offsets["Score"][6]) * 1000000 +
        high4(Pointers["Score"] + Offsets["Score"][7]) * 10000000
    )
}

function PlayerDestroyedObjects(count, value){
    return repeated(count, (Player["Score"] - prev(Player["Score"])) == value)
}

function CompletedStage3Challenge(){
    return IsValidSession(false) &&
        PlayerDestroyedObjects(50, 200) &&
        PlayerDestroyedObjects(12, 500) &&
        PlayerDestroyedObjects(12, 3000) &&
        PlayerReachedBoss(true) &&
        never(Stage["Id"] != Stages["Stage3"]) &&
        never(!IsInGame())
}
```
Generated logic:
![image](https://github.com/user-attachments/assets/8d9001a7-24fd-4de0-a90a-e82f63554ce1)

Expected logic (as updated manually in the Achievement Editor):
![image](https://github.com/user-attachments/assets/8b02b22e-5ed9-46ad-8faf-e4cfc4717ec4)

Just let me know if you need any additional information.

Thanks!

**Comment by TwosomesUP** [comment]
A shot in the dark, but it looks like `MemoryValueExpression.RebalanceForPointerChain` might be the culprit? When balancing AddSource + SubSource with the same pointer it might need to check for the same field type as well (MemoryAddress vs. PreviousValue).

**Comment by Jamiras** [comment]
You're close. The problem is in `RebalanceForPointerChain`, but it's discarding the modifier when it relocates the SubSource
```
var newRight = newLeft._memoryAccessors[i].MemoryAccessor;
```

It should probably just be ignoring modified accessors as the modifier is already a right-side.

**Comment by TwosomesUP** [comment]
Ah, that makes sense! Thanks Jamiras, I appreciate it.
