### ISSUE TITLE
Resets not attached to PauseIf when using disable_when

### ISSUE THREAD

**Issue by christianlegge** [Jamiras/RATools#511]
I'm using the following code to generate an achievement:

```
achievement(title = "Break-Off to a Good Start", description = "Pot a red ball on the break-off shot in Tournament or Quick Match mode.", points = 5,
    trigger =   disable_when(their_shot(), until = in_menu() || break_off()) &&
    in_game() && (in_tournament() || in_quick_match()) && !replay() && our_shot() &&
    trigger_when(prev(player_score()) < player_score())
)
```

I need to reset the pauselock when in the menu or break-off. It's important that these don't disable the achievement and instead reset *only* the pauselock because I'm trying to show a challenge icon during the break-off. This should be how disable_when generates the reset conditions according to the docs, but it doesn't work here. I've attached a screenshot of what generated vs. what I would expect (and have here edited it to).

![image](https://github.com/user-attachments/assets/696f9a24-e126-41cd-aa6c-ad7c9a969747)

**Comment by Jamiras** [comment]
If there aren't hits on any other conditions, the `ResetNextIf` gets turned into a `ResetIf`, and `ResetIf (A || B)` is the same as `ResetIf(A) || ResetIf(B)`. These changes look fine to me. I do find it curious that it's moving the Resets into an alt though.

Which other condition are you suggesting gets reset inappropriately?

**Comment by christianlegge** [comment]
> They have to be in an alt to not be affected by the PauseIf

No they don't - ResetNextIf is still evaluated when followed by a locked PauseIf, and that's the behavior I would expect from `disable_when(until)` (and is the behavior the docs describe).

The problem is that I'm using the reset condition as an "on button" - to reset the pauselock - rather than an "off button" which is how ResetIfs work by default. When they're in an alt group, they reset the pauselock correctly, but they reset the rest of the achievement too, which in this case is preventing my trigger icon from appearing (and in the worst case would prevent other hit counts from increasing if they were present, and prevent the achievement from triggering entirely if this reset condition were still true when it's supposed to unlock).

**Comment by Jamiras** [comment]
Okay, I think I see. The problem isn't that the ResetIf is logically incorrect, it's just that it makes the trigger icon disappear.

**Comment by christianlegge** [comment]
I mean, that makes it logically incorrect, no? It's disabling the rest of the achievement logic when it should only be resetting the pauselock. In this particular case the only effect is that it makes the icon disappear, but that's happening because the entire rest of the logic isn't being evaluated when it should be.

**Comment by Jamiras** [comment]
You may be right. This may affect more than just the trigger icon. If the ResetIf condition remains true, it will prevent the achievement from triggering.
