### ISSUE TITLE
[Feature request] Implement While loops and Do While loops

### ISSUE THREAD

**Issue by PopovMark** [Jamiras/RATools#512]
Self-explanatory. When you're making a self-contained function, you'll feel a need to iterate while X condition is going. I'm making a function to dot a score number to make it look good, and that's one example where this feature would be really nice to have.
Honestly I'm baffled why they aren't implemented yet, just about every programming language I know of has these.

**Comment by Jamiras** [comment]
`while` isn't implemented for many of the same reasons `continue` and `break` aren't implemented. All three implied a level of volatility not expected in a script that doesn't have any user inputs.

`while` in particular introduces a possible infinite loop, which is particularly dangerous with the compile-as-you-type behavior of RATools.
```
while (something) {}
```
could infinitely loop before the body was filled in.

`do...while` is just syntactic sugar for skipping over the conditional check of a `while` loop.

**Comment by Jamiras** [comment]
You can use recursion to simulate a while loop. Here's a solution for formatting a number (which is what I assume you mean by "dot a score number":
```
function add_commas(number)
{
    if (length(number) < 4)
        return number
        
    return add_commas(substring(number, 0, -3)) + "," + substring(number, -3)
}

function format_number(number)
{
    return add_commas(number + "") // convert to string
}
```

**Comment by PopovMark** [comment]
I understand.
I already did the function as needed without any recursion, it looks like ass but it works, lol.

**Comment by PopovMark** [comment]
They're not hardcoded btw
