### ISSUE TITLE
Small fixes to wiki

### ISSUE THREAD

**Issue by fomdt** [Jamiras/RATools#519]
Made some small fixes to wiki at https://github.com/fomdt/RATools/wiki (https://github.com/fomdt/RATools.wiki.git).
Compare revisions: https://github.com/fomdt/RATools/wiki/_compare/006e71f87c775ce4c581f463aabbb9729ec7f5c3.

**Comment by Jamiras** [comment]
I have made the suggested changes. Thanks for reporting them.
