### ISSUE TITLE
Bad arithmatic when comparing two bitmasked memory values

### ISSUE THREAD

**Issue by GauChoob** [Jamiras/RATools#529]
I think that the optimizer is cancelling out the bit masking on both sides of the equation? In any case, the program is outputting the wrong comparison, so it needs to be fixed or throw an error otherwise.

Please see this example:
[math.rascript.txt](https://github.com/user-attachments/files/17004348/math.rascript.txt)

In the meantime, I can workaround this issue by using bitcount/bits instead of bitmasking in my use case.

Thanks again!

**Comment by Jamiras** [comment]
"Funky" is actually working. 
`dword(X) & 0xFF` is just `byte(X)`, so you have `dword(X) & 0x7 > prev(byte(X))`. 
Similarly, `dword(X) & 0x07` can be simplified to `byte(X) & 0x07`, and the result is:
```
AddSource byte X & value 7
          0      > prev byte X
```

The other two cases are problematic and I will investigate.
