### ISSUE TITLE
Subtraction of offset accessor values causes unexpected results

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#54]
```
LEVEL = byte(0x96) + 1
PREV_LEVEL = prev(byte(0x96)) + 1

function advance_level() => LEVEL - PREV_LEVEL == 1
```

The expected result would be equivalent to the case where `LEVEL` and `PREV_LEVEL` are not offset, but in fact I get an underflow back to the maximum 32-bit value in the resulting value being compared.

Comparison (red: before removing offsets, green: after)
![image](https://user-images.githubusercontent.com/7488362/55446872-80236b80-558f-11e9-82fe-3c603f10879b.png)

Also note that `prev()` is marked on both sides of the equation (black line) in this comparison. That seems to be a separate issue. After updating the local set, it corrects itself. Will open a new issue if I can isolate why/when this happens.

**Comment by Jamiras** [comment]
Similar to a previous issue with multiplication, the `+1` within `PREV_LEVEL` was being factored out of the equation without consideration for the context it was in. Because it's within a subtraction, it should be treated as a `-1` for the transposing.
