### ISSUE TITLE
[Feature request] cli tool for script importer

### ISSUE THREAD

**Issue by jragauskas** [Jamiras/RATools#548]
Currently script import logic is inside 'New Script' dialog, while it could be in its own module and reused for a cli tool. This enables using RAScript with different editors easier. 

I am also utilizing current cli to develop under linux, but import currently still has to be done through VM environment.

**Comment by Jamiras** [comment]
There are a lot of options in the New Script dialog. If there were a CLI version, it would automatically always dump "All" assets, "All" memory addresses, "All" notes, and probably have a fixed function names setting as well.

**Comment by jragauskas** [comment]
I was not considering that. Anyway, that would still be better than nothing to me, but maybe not that useful to others.
