### ISSUE TITLE
[feature request] able to start a brand new script via RATools

### ISSUE THREAD

**Issue by meleu** [Jamiras/RATools#6]
I would like to jump the "[Create the script file](../wiki/Creating-a-Script-for-a-New-Game#create-the-script-file)".

I thought about an option in the File menu. The name could be `Start a new script`, and when activated it opens a small input box asking for the game ID (optional: make it accept numbers ony).

After entering the game ID and pressing OK, RATools fetch the game's title, and creates a file with the header, and then asks the users where to save the script file.

```
// Game Title
// #ID = XXX
```

**Comment by Jamiras** [comment]
I've replaced the "Dump Published" dialog with a "New Script" dialog. In this script, you can enter any game ID. If achievements exist, they will show up for dumping (similar to the previous implementation, but without loading them into the viewer first). If not, the dialog will remain empty and the script can be saved without any dumped achievements.

RATools still relies of the emulator caches to provide the game title and published achievements. It will report an error if the cached data is not found.

**Comment by meleu** [comment]
> RATools still relies of the emulator caches to provide the game title and published achievements.

Is it a "by design" feature?

I mean, you don't want network stuff on your code or you just don't want play with it for now?

**Comment by Jamiras** [comment]
There's plenty of network stuff in there, but it's all just scraping the website. The stuff used from the emulator cache is protected by a login token, and that's what i didn't want to implement - at least not initially.

I created a new feature request (https://github.com/Jamiras/RATools/issues/10) to add that functionality.
