### ISSUE TITLE
Point to RA emulator base directories instead of RACache\Data

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#76]
This is a request aiming to shorten the `RACacheDirectory` line in the configuration. Unless I missed the reason why the data directory must be pointed to directly, I think it is a safe change to make, as the directory structure is unlikely to change at this point, or at least no more likely than the data file names are.

**Comment by Jamiras** [comment]
Implemented in #80. The new ini field (without RACache\Data) is `EmulatorDirectories`. `RACacheDirectory` will be converted on load and replaced when saved.
