### ISSUE TITLE
Multiline comments

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#79]
This is a request for a new syntax feature. I sometimes want to comment out parts of a script, such as achievement definition blocks, without deleting them. It is quite tedious to do with single-line comments.

As far as I can tell, the standard `/*` and `*/` should not collide with other syntax.

**Comment by Dennis1543** [comment]
I would also love to see this implemented.

**Comment by BoomEXUK** [comment]
I tried this just now - I see the syntax highlighting works but the input is not accepted as valid. It would be great to see this implemented
![syntax-highlight](https://user-images.githubusercontent.com/16966330/232028812-16204fc1-1695-4455-aaba-da25a346ea75.png)
