### ISSUE TITLE
Multiple instances conflict with log file write access

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#9]
In v1.3.0, attempting to launch multiple instances of the application generates the following error: 

`Unhandled IOException: The process cannot access the file 'RATools.log' because it is being used by another process.`

Secondary instances then crash.

If exclusive log file access is necessary, then this error should be caught to exit secondary instances gracefully.

**Comment by Jamiras** [comment]
I was not expecting anyone to want to run multiple instances at the same time. I've modified the startup logic to iterate on the filename a few times before giving up instead of throwing an exception.
