### ISSUE TITLE
Wrong output for and'd conditions inside a never call

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#99]
The issue can be reproduced with the following code:

```
function never_not_in_room(room_id, game_mode) {
    return never(byte(0xabcd) != room_id
                 && byte(0xabce) == game_mode)
}

achievement(
    title="Test", description="Test", points=5,
    trigger=never_not_in_room(1, 2) && byte(0xabcf) == 111
)
```

The idea here is to reset when the player is in any room other than 1 whilst in "game mode" 2. This would mean that the cheevo is free to trigger whilst the player is in room 1, regardless of game mode.

I expected this to be generated:
```
AndNext byte(0xabcd) != 1
ResetIf byte(0xabce) == 2
        byte(0xabcf) == 111
```

Instead, RATools generates this:
```
AndNext byte(0xabcd) != 1
        byte(0xabce) != 2     // flipped operator + no ResetIf
        byte(0xabcf) == 111
```

This generated code is not equivalent to what I expected. For example, it won't accept the player being in room 1 at all.

----

I should note that I had already used this pattern in other achievements without running into the issue. The reason seems to be that using hits in the achievement forces the `ResetIf` to be generated. For example, adding a `once` call around `byte(0xabcf) == 111` causes the code I expected to be generated.

**Comment by Jamiras** [comment]
When no hit requirements are preset, a ResetIf is inverted. It's just not inverting the AndNext clause too.

**Comment by Jamiras** [comment]
To invert the AndNext, we need to replace it with an OrNext, or convert the two sides of the AndNext into Alt groups. Since we've already done the combinatorial AND/OR expansion, I've decided to just remove this optimization and leave the PauseIf/ResetIf if an AndNext is present.
